AWSTemplateFormatVersion: '2010-09-09'
Description: Leverages the Ocean Best Practices RSS feed to discover documents needing
  ingest.
Outputs:
  AvailableDocumentTopicArn:
    Description: The topic ARN for available document subscribers.
    Value:
      Ref: AvailableDocumentTopic
Parameters:
  Environment:
    Default: staging
    Description: staging, prod, or a development environment uniquely named across
      CF templates like stark
    Type: String
  ScheduleInterval:
    Default: 300
    Description: The amount of time in seconds to consider published documents valid
      to index. Also may just be how often this function is scheduled to run by e.g.
      CloudWatch events.
    Type: Number
Resources:
  AvailableDocumentTopic:
    Properties:
      DisplayName:
        Fn::Sub: Available Documents Topic-#{Environment}
    Type: AWS::SNS::Topic
  InvokeSchedulerFromEventPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - SchedulerFunction
        - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - SchedulerEventRule
        - Arn
    Type: AWS::Lambda::Permission
  SchedulerEventRule:
    Properties:
      Description: Schedules the RSS checker (scheduler) to execute at a specific
        interval
      Name:
        Fn::Sub: obp-scheduler-interval-rule-${Environment}
      ScheduleExpression: rate(5 minutes)
      State: ENABLED
      Targets:
      - Arn:
          Fn::GetAtt:
          - SchedulerFunction
          - Arn
        Id:
          Fn::Sub: scheduler-event-id-${Environment}
    Type: AWS::Events::Rule
  SchedulerExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - SNS:Publish
            Effect: Allow
            Resource:
              Ref: AvailableDocumentTopic
          Version: '2012-10-17'
        PolicyName: AllowPublishToDocumentTopic
      RoleName:
        Fn::Sub: obp-scheduler-execution-role-${Environment}
    Type: AWS::IAM::Role
  SchedulerFunction:
    Properties:
      CodeUri: s3://obp-scheduler-functions-prod/025eb56c1c738d045ba7137c81bb2da5
      Description: Periodically checks the OBP RSS feed for documents that need indexing.
      Environment:
        Variables:
          DOCUMENT_TOPIC_ARN:
            Ref: AvailableDocumentTopic
          SCHEDULE_INTERVAL:
            Ref: ScheduleInterval
      FunctionName:
        Fn::Sub: obp-scheduler-function-${Environment}
      Handler: scheduler.handler
      Role:
        Fn::GetAtt:
        - SchedulerExecutionRole
        - Arn
      Runtime: nodejs6.10
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
