export const GET_STATS = 'GET_STATS';
export const STATS_HAS_ERRORED = "STATS_HAS_ERRORED";
export const STATS_IS_LOADING = "STATS_IS_LOADING";
export const STATS_FETCH_DATA_SUCCESS = "STATS_FETCH_DATA_SUCCESS";
