export const GET_TAGS = 'GET_TAGS';
export const TAGS_HAS_ERRORED = "TAGS_HAS_ERRORED";
export const TAGS_IS_LOADING ="TAGS_IS_LOADING";
export const TAGS_FETCH_DATA_SUCCESS = "TAGS_FETCH_DATA_SUCCESS";
export const GET_TAGS_CSV = 'GET_TAGS_CSV';
export const TAGS_CSV_HAS_ERRORED = "TAGS_CSV_HAS_ERRORED";
export const TAGS_CSV_IS_LOADING ="TAGS_CSV_IS_LOADING";
export const TAGS_CSV_FETCH_DATA_SUCCESS = "TAGS_CSV_FETCH_DATA_SUCCESS";
